name: Build SuperRyzen Kernel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build SuperRyzen Kernel
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
          wget https://raw.githubusercontent.com/find-404/opo/main/build-start.sh
          bash build-start.sh stable clang
          cd kernel
          mkdir kernel-done
          wget https://raw.githubusercontent.com/find-404/opo/main/build-dtb.sh
          bash build-dtb.sh a26x clang qpnp
          bash build-dtb.sh lavender clang qpnp
          bash build-dtb.sh tulip clang qpnp
          bash build-dtb.sh whyred clang qpnp
          git apply qti.patch
          bash build-dtb.sh a26x clang qti
          bash build-dtb.sh lavender clang qti
          bash build-dtb.sh tulip clang qti
          bash build-dtb.sh whyred clang qti
          git restore .
          wget https://raw.githubusercontent.com/find-404/opo/main/build.sh
          bash build.sh a26x newcam clang
          bash build.sh a26x oldcam clang
          bash build.sh a26x tencam clang
          bash build.sh lavender newcam clang
          bash build.sh lavender oldcam clang
          bash build.sh tulip newcam clang
          bash build.sh tulip oldcam clang
          bash build.sh whyred newcam clang
          bash build.sh whyred oldcam clang
          git apply oc.patch
          bash build-dtb.sh tulip clang qpnp
          bash build-dtb.sh whyred clang qpnp
          git apply qti.patch
          bash build-dtb.sh tulip clang qti
          bash build-dtb.sh whyred clang qti
          git restore .
          bash build.sh tulip newcam oc clang
          bash build.sh tulip oldcam oc clang
          bash build.sh whyred newcam oc clang
          bash build.sh whyred oldcam oc clang
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: tulip
          path: kernel/ak3-tulip/*
                
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SuperRyzen-CAF_a26x_v7_newcam
          path: kernel/kernel-done/SuperRyzen-CAF_a26x_v7_newcam.zip
          
                          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SuperRyzen-CAF_a26x_v7_oldcam.zip
          path: kernel/kernel-done/SuperRyzen-CAF_a26x_v7_oldcam.zip
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SuperRyzen-CAF_a26x_v7_tencam.zip
          path: kernel/kernel-done/SuperRyzen-CAF_a26x_v7_tencam.zip
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SuperRyzen-CAF_lavender_v7_newcam.zip
          path: kernel/kernel-done/SuperRyzen-CAF_lavender_v7_newcam.zip
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SuperRyzen-CAF_lavender_v7_oldcam.zip
          path: kernel/kernel-done/SuperRyzen-CAF_lavender_v7_oldcam.zip
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SuperRyzen-CAF_tulip_v7_newcam.zip
          path: kernel/kernel-done/SuperRyzen-CAF_tulip_v7_newcam.zip
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SuperRyzen-CAF_tulip_v7_oldcam.zip
          path: kernel/kernel-done/SuperRyzen-CAF_tulip_v7_oldcam.zip
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SuperRyzen-CAF_tulip_v7-OC_newcam.zip
          path: kernel/kernel-done/SuperRyzen-CAF_tulip_v7-OC_newcam.zip
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SuperRyzen-CAF_tulip_v7-OC_oldcam.zip
          path: kernel/kernel-done/SuperRyzen-CAF_tulip_v7-OC_oldcam.zip
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SuperRyzen-CAF_whyred_v7_newcam.zip
          path: kernel/kernel-done/SuperRyzen-CAF_whyred_v7_newcam.zip
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SuperRyzen-CAF_whyred_v7_oldcam.zip
          path: kernel/kernel-done/SuperRyzen-CAF_whyred_v7_oldcam.zip
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SuperRyzen-CAF_whyred_v7-OC_newcam.zip
          path: kernel/kernel-done/SuperRyzen-CAF_whyred_v7-OC_newcam.zip
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SuperRyzen-CAF_whyred_v7-OC_oldcam.zip
          path: kernel/kernel-done/SuperRyzen-CAF_whyred_v7-OC_oldcam.zip

    
