name: Build SuperRyzen Kernel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build SuperRyzen Kernel
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
          wget https://raw.githubusercontent.com/find-404/opo/main/build-start.sh
          bash build-start.sh stable clang
          cd kernel
          rm build-dtb.sh
          rm build.sh
          wget https://raw.githubusercontent.com/find-404/opo/main/build-dtb.sh
          bash build-dtb.sh tulip clang qpnp
          git apply qti.patch
          bash build-dtb.sh tulip clang qti
          git restore .
          wget https://raw.githubusercontent.com/find-404/opo/main/build.sh
          bash build.sh tulip oldcam clang
          git apply qti.patch
          bash build-dtb.sh tulip clang qti
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: tulip
          path: kernel/ak3-tulip/*          

    
